# image: node:4.7.3
# defaults to atlassian/default-image:latest

pipelines:
  tags:
    v*:
      - step:
          script:
            - npm install
            - npm run sass
            - npm run compiler
            - rsync -avzc --delete --exclude=.htaccess --exclude=404.shtml src_compiled/ witvliet@107.180.1.16:nemanode_public/html/
  custom:
    test:
      - step:
          caches:
            - node
          script:
            - npm install
            - npm test
    transfer-dev-to-server:
      - step:
          script:
            - npm install
            - npm run sass
            - rsync -avzc --delete --exclude=.htaccess src/ witvliet@107.180.1.16:nemanode_dev/html/

